import { createTrees, WidgetProps } from './lib'
import * as serviceWorker from './serviceWorker'

// This set-up is done manually in the Rudolf demo page
// In a Carnap book chapter, this code is generated by a pandoc filter
const trees: WidgetProps[] = [
  {
    elementId: 'problem-1.1',
    initialPremises: 'P->Q,P,~Q',
    checker: 'checkIchikawaJenkinsSLTableau',
    debug: true,
  },
  {
    elementId: 'problem-1.2',
    checker: 'checkIchikawaJenkinsSLTableau',
    initialPremises: '',
    debug: true,
  },
  {
    elementId: 'problem-1.3',
    checker: 'checkIchikawaJenkinsQLTableau',
    initialPremises: 'Ax(Px->Qx),~Qa,~~Pa',
    debug: true,
  },
]

createTrees(trees)

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister()
